import base64
import hashlib
import hmac
import os
from fastapi import HTTPException
from typing import Tuple


def generate_pkce_pair() -> Tuple[str, str]:
    """
    Generate a PKCE code_verifier and code_challenge using the S256 method.

    This follows RFC 7636 and OAuth 2.1 requirements:
    - code_verifier is a high-entropy cryptographically random string
      (43–128 characters, URL-safe, no padding)
    - code_challenge is BASE64URL-encoded SHA256 hash of the verifier

    Returns:
        Tuple[str, str]:
            - code_verifier: Secret value to be stored client-side and sent
              only to the token endpoint.
            - code_challenge: Public value derived from the verifier, safe
              to send in the authorization request.
    """

    # 32 bytes of entropy → 43-character base64url string (minimum allowed)
    code_verifier: str = (
        base64.urlsafe_b64encode(os.urandom(32))
        .rstrip(b"=")
        .decode("ascii")
    )

    # S256 challenge: BASE64URL(SHA256(code_verifier))
    code_challenge: str = (
        base64.urlsafe_b64encode(
            hashlib.sha256(code_verifier.encode("ascii")).digest()
        )
        .rstrip(b"=")
        .decode("ascii")
    )

    return code_verifier, code_challenge

def verify_pkce(code_verifier: str, stored_code_challenge: str) -> None:
    """
    Verify a PKCE code_verifier against a previously stored S256 code_challenge.

    This function implements PKCE verification as defined in RFC 7636 and
    required by OAuth 2.1. It recomputes the S256 code challenge from the
    provided verifier and compares it to the stored challenge using a
    constant-time comparison.

    Args:
        code_verifier: The original high-entropy secret generated by the client
            and sent to the token endpoint.
        stored_code_challenge: The S256 code challenge value stored during the
            authorization request.

    Raises:
        HTTPException: If the computed challenge does not match the stored
            code_challenge, indicating PKCE verification failure.
    """

    computed_challenge: str = (
        base64.urlsafe_b64encode(
            hashlib.sha256(code_verifier.encode("ascii")).digest()
        )
        .rstrip(b"=")
        .decode("ascii")
    )

    if not hmac.compare_digest(computed_challenge, stored_code_challenge):
        raise HTTPException(400, "Code verification failed")
